### PR TITLE
Fix RPC Pushes

### PR DESCRIPTION
**Pull request by mike-koch**
Apparently `{}` is needed after `discord::Activity activity` ... just shows how much I know about C++ 😅 

Also implemented execution of Discord callbacks via `OnDraw3D` calls, just to make things proper.

### CODE REVIEW

**Comment by OrfeasZ** [comment]
`OnDraw3D` can be called multiple times per frame when multi-frame buffering is on. A better alternative would probably be to use `Globals::GameLoopManager->RegisterFrameUpdate`.

**Comment by mike-koch** [comment]
@OrfeasZ - Switched from `OnDraw3D` to `RegisterFrameUpdate`.  Let me know if anything else looks off to you!

**Comment by OrfeasZ** [comment]
@mike-koch `eUpdatePlayMode` will only make the callback be called while you're in-game, so it won't work while paused or in the main menu. I'd suggest using `eUpdateAlways` instead.

**Comment by mike-koch** [comment]
> @mike-koch `eUpdatePlayMode` will only make the callback be called while you're in-game, so it won't work while paused or in the main menu. I'd suggest using `eUpdateAlways` instead.

Switched to `eUpdateAlways`

**Pull request merged**
